export default {
  index: {
    hanShu: '函数',
    qiuHe: '求和1(,)',
    qiuHe2: '求和1',
    tuiChuQuanPing: '退出全屏',
    quanPing: '全屏',
    iNTAS:
      'int a = 100;\n    string s = #sum("hello",@hahahdsdhjbewdbu0);\n    double d=777.324;\n    boolean x = a >= 0;\n    list result = [x, d, 333];\n    "或为空";\n    且\n    或\n   @hahahdsdhjbewdbu0 && @hahahdsdhjbewdbu0 || @hahahdsdhjbewdbu2',
    jieKuanRenShenFen: '借款人身份证',
    jieKuanRen: '借款人',
    jieKuanRenXingMing: '借款人姓名',
    shiJiFangKuanJin: '实际放款金额',
    fangKuanJinE: '放款金额',
    zuiXiaoZhi: '最小值4(,)',
    zuiXiaoZhi2: '最小值4',
    zuiDaZhi: '最大值3(,)',
    zuiDaZhi2: '最大值3',
    pingJunZhi: '平均值2(,)',
    pingJunZhi2: '平均值2',
    zuiXiaoZhi3: '最小值(,)',
    zuiXiaoZhi4: '最小值',
    zuiDaZhi3: '最大值(,)',
    zuiDaZhi4: '最大值',
    pingJunZhi3: '平均值(,)',
    pingJunZhi4: '平均值',
    qiuHe3: '求和(,)',
    qiuHe4: '求和',
    ziDuanHaXinDai: '[字段]哈信贷测试',
    ziDuanCeShiShi: '[字段]测试试{val1}',
  },
};
